// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd_HkDKJFlcsF175TTkfKGlRqUmlr1clc',
    appId: '1:256516531499:web:75ccedfed5ea5de5e8d16e',
    messagingSenderId: '256516531499',
    projectId: 'capstone-629a7',
    authDomain: 'capstone-629a7.firebaseapp.com',
    storageBucket: 'capstone-629a7.appspot.com',
    measurementId: 'G-7RKRFTVKD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_baWV2LDJQ1oc2rMg78VN0LhgeJM7phM',
    appId: '1:256516531499:android:39e488fcf71559d5e8d16e',
    messagingSenderId: '256516531499',
    projectId: 'capstone-629a7',
    storageBucket: 'capstone-629a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQnxQ0LTTUFnpYjIIQUyT5lkYTq03MfI',
    appId: '1:256516531499:ios:242597d16f1ed636e8d16e',
    messagingSenderId: '256516531499',
    projectId: 'capstone-629a7',
    storageBucket: 'capstone-629a7.appspot.com',
    iosClientId: '256516531499-g5mrs20j2cl0rn32o8hnfem9fbbqn4bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoQnxQ0LTTUFnpYjIIQUyT5lkYTq03MfI',
    appId: '1:256516531499:ios:242597d16f1ed636e8d16e',
    messagingSenderId: '256516531499',
    projectId: 'capstone-629a7',
    storageBucket: 'capstone-629a7.appspot.com',
    iosClientId: '256516531499-g5mrs20j2cl0rn32o8hnfem9fbbqn4bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneApp',
  );
}
